version: '3'

services: 
  saca:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: saca
    ports:
    - "80:5800"
    - "443:443"
    environment:
      ConnectionStrings__DefaultConnection: "Host=saca_db;Port=5432;Database=SACA;User ID=postgres;Password=123qwe"
      DB_CONNECTION_STRING: "Host=saca_db;Port=5432;Database=SACA;User ID=postgres;Password=123qwe"
      ASPNETCORE_URLS: "http://*:5800;https://*:443"
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
      # - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - mynetwork

  db:
    image: postgres:10
    container_name: saca_db
    restart: always
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      # POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata_compose
    volumes:
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ${USERPROFILE}\docker\volumes\databases\postgres\pgdata:/var/lib/postgresql/data/pgdata_compose
    ports:
      - 5432:5432
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

  