name: Digital Ocean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

# deploy:
#   runs-on: ubuntu-latest
#   needs: build

#   steps:
#     - uses: actions/checkout@v2

#     - name: Deploy to droplet using SSH
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.DO_HOST }}
#         username: ${{ secrets.DO_USERNAME }}
#         password: ${{ secrets.DO_PASSWORD }}
#         # key: ${{ secrets.DO_PRIVATE_KEY }}
#         debug: true
#         script: |
#           logname
#           sudo systemctl stop saca
#           export AppOptions__Token__SecurityKey=${{ secrets.APPOPTIONS__TOKEN__SECURITYKEY }}
#           export CloudinaryOptions__ApiEnvironmentVariable=${{ secrets.CLOUDINARYOPTIONS__APIENVIRONMENTVARIABLE }}
#           cd ${{ secrets.DO_DOCROOT }}
#           git pull
#           dotnet build -c Release
#           dotnet publish -c Release
#           dotnet-ef database update
#           sudo systemctl start saca
