name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 6.0.x

#       - name: Restore
#         run: dotnet restore
      
#       - name: Build
#         run: dotnet build --configuration Release --no-restore
    
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - uses: actions/checkout@v2
#       - run: docker build -t t4zo/saca src/.
#       - run: echo "${{secrets.DOCKERHUB_ACCESS_TOKEN}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
#       - run: docker push t4zo/saca