name: Docker

on:
  # workflow_run:
  #   workflows: 
  #     - build
  #   branches: 
  #     - main
  #   types:
  #     - completed

  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  # push:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}

  #   environment:
  #     name: Development

  #   env:
  #     DOCKERHUB_USER_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB__IMAGE_TAG }}
  #     GITHUB_USER_IMAGE_TAG: ${{ github.repository_owner }}/${{ secrets.DOCKERHUB__IMAGE_TAG }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Build
  #       run: docker build -f src/Dockerfile -t ${{ env.GITHUB_USER_IMAGE_TAG }} ./src

  #     - name: Login DockerHub
  #       run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ github.repository_owner }} --password-stdin

  #     - name: Push
  #       run: docker push ${{ env.GITHUB_USER_IMAGE_TAG }}
        

# buildx failed with: ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount3174352312/Dockerfile: no such file or directory
  # push:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  #         ecr: auto
  #         logout: true

  #     - name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./src
  #         push: ${{ github.ref == 'refs/heads/main' }}
  #         tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB__IMAGE_TAG}}
