name: Amazon EC2

on:
  workflow_run:
    workflows: 
      - docker
    branches: 
      - main
    types:
      - completed

  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  # DeployDev:
  #   needs: [Build]
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: Development
  #     url: 'https://saca.t4zo.com/health'

  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Create CodeDeploy Deployment
  #       id: deploy
  #       run: |
  #         aws deploy create-deployment \
  #           --application-name saca \
  #           --deployment-group-name saca-dev \
  #           --deployment-config-name CodeDeployDefault.AllAtOnce \
  #           --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
  #           --file-exists-behavior=OVERWRITE \
  #           --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE
