name: Amazon ECS

on:
  workflow_run:
    workflows: 
      - docker
    branches: 
      - main
    types:
      - completed

  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update ECS Cluster Service
        id: deploy
        run: |
          aws ecs update-service --cluster ${{ secrets.AWS_ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy to EC2 using SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         # key: ${{ secrets.PRIVATE_KEY }}
  #         debug: true
  #         script: |
  #           logname
  #           sudo docker container stop saed
  #           sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB__IMAGE_TAG}}
  #           sudo docker container prune -f
  #           sudo docker container ${{ secrets.DOCKER_RUN }}
